# Generated by Django 2.2.8 on 2020-02-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20200227_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
