# Generated by Django 2.2.8 on 2020-02-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_employee_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Training group',
                'verbose_name_plural': 'Training groups',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('training_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.TrainingGroup')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Training',
                'ordering': ('title', 'training_group'),
            },
        ),
    ]
