# Generated by Django 2.2.8 on 2020-02-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_training_traininggroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='department',
        ),
        migrations.RemoveField(
            model_name='job',
            name='position',
        ),
        migrations.RemoveField(
            model_name='training',
            name='training_group',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.DeleteModel(
            name='TrainingGroup',
        ),
    ]
