# Generated by Django 2.2.8 on 2020-02-29 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_employee_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.Training'),
        ),
    ]
