# Generated by Django 2.2.8 on 2020-02-29 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='training',
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'R'), (False, 'N/R')], default=False)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.Job')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.Training')),
            ],
            options={
                'verbose_name': 'Matrix',
                'verbose_name_plural': 'Matrix',
                'ordering': ('job', 'training', 'status'),
            },
        ),
    ]
