# Generated by Django 2.2.8 on 2020-03-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_auto_20200318_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='badge',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
