# Generated by Django 2.2.8 on 2020-03-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_auto_20200318_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('department',), 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('position',), 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.RemoveField(
            model_name='position',
            name='title',
        ),
        migrations.AddField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
