# Generated by Django 2.2.8 on 2020-03-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_auto_20200322_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
