# Generated by Django 2.2.8 on 2020-03-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_auto_20200322_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
