# Generated by Django 2.2.8 on 2020-03-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_auto_20200323_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='training',
            field=models.ManyToManyField(to='training.Training'),
        ),
    ]
