# Generated by Django 3.0.4 on 2020-03-24 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_auto_20200324_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.Department')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.Position')),
                ('training', models.ManyToManyField(to='training.Training')),
            ],
            options={
                'verbose_name': 'Training Assignement',
                'verbose_name_plural': 'Training Assignements',
                'ordering': ('department', 'position'),
            },
        ),
    ]
