# Generated by Django 3.0.4 on 2020-03-24 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_trainingmatrix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingmatrix',
            options={'ordering': ('department', 'position'), 'verbose_name': 'Training Matrix', 'verbose_name_plural': 'Training Assignements'},
        ),
    ]
