# Generated by Django 3.0.4 on 2020-03-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_auto_20200324_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingmatrix',
            options={'ordering': ('department', 'position'), 'verbose_name': 'Training Assignement', 'verbose_name_plural': 'Training Matrix'},
        ),
    ]
