# Generated by Django 3.0.4 on 2020-03-24 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_auto_20200324_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.TrainingMatrix'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
