# Generated by Django 3.0.4 on 2020-04-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0028_auto_20200324_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.AddField(
            model_name='employee',
            name='cost_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costCode', to='training.Location'),
        ),
        migrations.AddConstraint(
            model_name='trainingmatrix',
            constraint=models.UniqueConstraint(fields=('department', 'position'), name='job'),
        ),
    ]
