# Generated by Django 3.0.4 on 2020-04-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0029_auto_20200425_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
