# Generated by Django 3.0.4 on 2020-04-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0030_auto_20200425_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.TrainingMatrix'),
        ),
    ]
