# Generated by Django 3.0.4 on 2020-04-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0033_employee_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='project',
        ),
    ]
