# Generated by Django 3.0.4 on 2020-04-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0037_requiredtraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkjob', to='training.TrainingMatrix'),
        ),
        migrations.AddField(
            model_name='trainingmatrix',
            name='job',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
