# Generated by Django 3.0.4 on 2020-04-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0038_auto_20200428_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='training',
        ),
        migrations.AlterField(
            model_name='trainingmatrix',
            name='job',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
