# Generated by Django 3.0.4 on 2020-04-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0039_auto_20200428_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='badge',
            field=models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
