# Generated by Django 3.0.4 on 2020-04-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0040_auto_20200428_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='badge',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
