# Generated by Django 3.0.4 on 2020-04-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0044_auto_20200428_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ifmt',
            field=models.FileField(blank=True, null=True, upload_to='IFMT'),
        ),
    ]
