# Generated by Django 3.0.4 on 2020-05-02 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0045_auto_20200428_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.TrainingMatrix', to_field='job'),
        ),
    ]
